AWSTemplateFormatVersion: 2010-09-09
Description: Basic EC2 instance
Resources:
  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-0ce933e2ae91880d3
      InstanceType: t2.micro
      KeyName: mydevopskey
      SecurityGroups:
        - default
        - !Ref SSHSecurityGroup     
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow tcp ssh to client host
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0